### ISSUE TITLE
Type of coding used for DANCE

### ISSUE THREAD

**Issue by Squiddu** [Luxiono/D.A.N.C.E#1]
Which way should I make this game? React below.

Heart = C#
Rocket = Unity

**Comment by Squiddu** [comment]
It has been decided that the game will only be coded in C#. Closing this.

**Comment by andy840119** [comment]
Both osu-framework and Unity use C#
So maybe it's better to decide this game will design as 2D or 3D.
Also, will this game be part of the osu! client's ruleset?
.
If you want to make cross-platform game by just coding, another choice is [monogame](http://www.monogame.net/)
